baseurl = "http://phamviet.net/"
title = "Viet Pham"
languageCode = "en-us"
# theme = "hugo-highlights-theme"

[params]

  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Fontawesom's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engings feel free to add a few informations.
  # This lines will be inserted as meta tags.
  name = "Viet Pham"
  description = "Personal website"

  # For a static site it's not possible to provide a contact form. The contact form uses
  # www.formspree.io as a proxy. The form makes a Post request to their servers to send an email
  # Visitors can send up to a 1000 emails each month
  #
  # How to setup formspree
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email to yourself to confirm your account
  # - click the confirmation link in the email from www.formspree.io
  # - That's all. Enjoy mailing!
  email = "phpcodervn@gmail.com"

  # If this param is set to true, every section gets an own background image (located at static/images)
  # to change the image you could use the param picture on every section.
  # If it's disabled you could change the background to overwrite the bg.png and overlay.png to set the background.
  backgroundpersection = true
  enableRobotsTXT = true
  # Hero Section
  [params.hero]
    title = "Viet Pham"
    description = "Helo"
    buttontext = "begin"

  # about section
  [params.about]
    enable = true
    title = "Who am I"
    description = "Fullstack Developer"
    buttontext = "next"
    # the picture is storead at static/images/
    picture = "pic01.jpg"

    # working section
  [params.languages]
    enable = true
    title = "Programming Languages"
    description = "#php #python #ruby #go #javascript"
    buttontext = "next"
    picture = "pic02.jpg"

    # working section
  [params.working]
    enable = true
    title = "Thing i'm working on"
    description = "ERPNext Customization"
    buttontext = "next"
    picture = "pic03.jpg"

  # skill section
  [params.skill_list]
    enable = true
    title = "Stuff I do"
    description = "Consequat sed ultricies rutrum. Sed adipiscing eu amet interdum lorem blandit vis ac commodo aliquet vulputate."
    buttontext = "next"
    # the picture is storead at static/images/
    picture = "pic01.jpg"

    [[params.skills]]
      icon = "fa-code"
      title = "Write Code"

    [[params.skills]]
      icon = "fa-search"
      title = "Researching"

    [[params.skills]]
        icon = "fa-beer"
        title = "Drinking"

  # infos section
  [params.infos]
    enable = true
    title = "One more thing"
    description = "Nothing ^_^!"
    # the picture is storead at static/images/
    picture = "pic02.jpg"

  # footer section
  # this section includes
  #
  # - the contact form
  # - social icons
  #
  # It's possible to disable the whole footer or disable only social icons or contact form

  [params.footer]
    enable = true
    title = "Get in Touch"

    # contact form
    [params.footer.contact]
      enable = true

    [params.footer.contact.form]
      name = "Name"
      email = "Your Email"
      message = "Your Message"
      buttontext = "send message"

    # social icons
    [params.footer.social_list]
      enable = true

      [[params.footer.social]]
        title = "Twitter"
        icon = "fa-twitter"
        link = "#"

      [[params.footer.social]]
        title = "Facebook"
        icon = "fa-facebook"
        link = "#"

      [[params.footer.social]]
        title = "Instagramm"
        icon = "fa-instagram"
        link = "#"

      [[params.footer.social]]
        title = "Dribbble"
        icon = "fa-dribbble"
        link = "#"

      [[params.footer.social]]
        title = "Email"
        icon = "fa-envelope"
        link = "#"

    # copyright
    #[params.footer.copyright.notice]

      [[params.footer.copyright.notice]]
        text = "© Viet Pham"
